delimiter $$

CREATE TABLE `WENZINS`.`PATIENT_ADDRESS` (
  `ADDRESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS_LINE1` varchar(255) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(255) DEFAULT NULL,
  `ADDRESS_TYPE` varchar(255) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `DISTRICT` varchar(255) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `PHONE_NUMBER` varchar(255) DEFAULT NULL,
  `PHONE_TYPE` varchar(255) DEFAULT NULL,
  `PIN_CODE` varchar(255) DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `patient_PATIENT_ID` bigint(20) DEFAULT NULL,
  `PATIENT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`),
  UNIQUE KEY `ADDRESS_ID` (`ADDRESS_ID`),
  KEY `FK8BF3907A39C2D593` (`PATIENT_ID`),
  KEY `FK8BF3907A31349B0D` (`patient_PATIENT_ID`),
  CONSTRAINT `FK8BF3907A31349B0D` FOREIGN KEY (`patient_PATIENT_ID`) REFERENCES `PATIENT` (`PATIENT_ID`),
  CONSTRAINT `FK8BF3907A39C2D593` FOREIGN KEY (`PATIENT_ID`) REFERENCES `PATIENT` (`PATIENT_ID`)
);

CREATE TABLE `WENZINS`.`PATIENT` (
  `PATIENT_ID` bigint(20) NOT NULL,
  `DOB` datetime DEFAULT NULL,
  `EMERGENCY_CONTACT_NAME` varchar(255) DEFAULT NULL,
  `EMERGENCY_RELATIONSHIP` varchar(255) DEFAULT NULL,
  `FIRSTNAME` varchar(255) DEFAULT NULL,
  `MIDDLENAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `MOBILE` varchar(255) DEFAULT NULL,
  `PHONE_RESIDENCE` varchar(255) DEFAULT NULL, 
  `PHONE_OFFICE` varchar(255) DEFAULT NULL, 
  `PATIENT_GENDER` varchar(255) DEFAULT NULL,
  `LASTNAME` varchar(255) DEFAULT NULL,
  `OCCUPATION` varchar(255) DEFAULT NULL,
  `UHID` varchar(255) NOT NULL,
  PRIMARY KEY (`PATIENT_ID`),
  UNIQUE KEY `PATIENT_ID` (`PATIENT_ID`),
  UNIQUE KEY `UHID` (`UHID`)
);

